# Gitlab repository link: https://gitlab.com/ErickGiffoni/GCES-Workshop-CI-Entrega-02
stages:
  - build
  - test
  - deploy

# Usa uma imagem Docker do Docker para CI
image: docker:20.10.8

services:
  # Docker in Docker: usa para fazer build usando o Dockerfile
  - docker:dind

build-front:
  image: node:14
  stage: build
  before_script:
    - echo "[.] Building frontend..."
    - npm install -g npm@latest
  script:
    - cd frontend
    - npm install
  after_script:
    - echo "[x] Successfully built frontend !"