# Gitlab repository link: https://gitlab.com/ErickGiffoni/GCES-Workshop-CI-Entrega-02
stages:
  - build
  - test
  - deploy

# Usa uma imagem Docker do Docker para CI
image: docker:20.10.8

services:
  # Docker in Docker: usa para fazer build usando o Dockerfile
  - docker:dind

variables:
  PROJECT_NAME: ErickGiffoni_GCES_entrega02

build-front:
  stage: build
  before_script:
    - echo "[.] Building frontend..."
  script:
    # Faz o build do frontend usando o Docker
    - docker build -f ./frontend/Dockerfile -t $PROJECT_NAME:build ./frontend
    # Faz login no Docker
    - docker login -u $docker_user -p $docker_password
    # Publica a imagem construida no Docker Hub do $docker_user
    - docker push $PROJECT_NAME:build
  after_script:
    - echo "[x] Successfully built frontend !"

build-backend:
  stage: build
  before_script:
    - echo "[.] Building backend..."
  script:
    # Faz o build do backend usando o Docker
    - docker build -f ./backend/Dockerfile -t $PROJECT_NAME:build-back ./backend
    # Faz login no Docker
    - docker login -u $docker_user -p $docker_password
    # Publica a imagem construida no Docker Hub do $docker_user
    - docker push $PROJECT_NAME:build-back
  after_script:
    - echo "[x] Successfully built backend !"

test-frontend:
  stage: test
  before_script:
    - echo "[.] Testing frontend..."
  script:
    # Usa o proprio docker-compose para o teste, passando como entrypoint
    # o comando a ser executado
    - docker-compose run --entrypoint "npm run coverage" frontend
  after_script:
    - echo "[x] Frontend successfully tested !"